// Code generated by entc, DO NOT EDIT.

package club

import (
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/pattapong1/app/ent/predicate"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Club {
	return predicate.Club(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Club {
	return predicate.Club(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Club {
	return predicate.Club(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Club {
	return predicate.Club(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Club {
	return predicate.Club(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Club {
	return predicate.Club(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Club {
	return predicate.Club(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Club {
	return predicate.Club(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Club {
	return predicate.Club(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// CLUBNAME applies equality check predicate on the "CLUB_NAME" field. It's identical to CLUBNAMEEQ.
func CLUBNAME(v string) predicate.Club {
	return predicate.Club(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCLUBNAME), v))
	})
}

// CLUBNAMEEQ applies the EQ predicate on the "CLUB_NAME" field.
func CLUBNAMEEQ(v string) predicate.Club {
	return predicate.Club(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCLUBNAME), v))
	})
}

// CLUBNAMENEQ applies the NEQ predicate on the "CLUB_NAME" field.
func CLUBNAMENEQ(v string) predicate.Club {
	return predicate.Club(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCLUBNAME), v))
	})
}

// CLUBNAMEIn applies the In predicate on the "CLUB_NAME" field.
func CLUBNAMEIn(vs ...string) predicate.Club {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Club(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldCLUBNAME), v...))
	})
}

// CLUBNAMENotIn applies the NotIn predicate on the "CLUB_NAME" field.
func CLUBNAMENotIn(vs ...string) predicate.Club {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Club(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldCLUBNAME), v...))
	})
}

// CLUBNAMEGT applies the GT predicate on the "CLUB_NAME" field.
func CLUBNAMEGT(v string) predicate.Club {
	return predicate.Club(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCLUBNAME), v))
	})
}

// CLUBNAMEGTE applies the GTE predicate on the "CLUB_NAME" field.
func CLUBNAMEGTE(v string) predicate.Club {
	return predicate.Club(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCLUBNAME), v))
	})
}

// CLUBNAMELT applies the LT predicate on the "CLUB_NAME" field.
func CLUBNAMELT(v string) predicate.Club {
	return predicate.Club(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCLUBNAME), v))
	})
}

// CLUBNAMELTE applies the LTE predicate on the "CLUB_NAME" field.
func CLUBNAMELTE(v string) predicate.Club {
	return predicate.Club(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCLUBNAME), v))
	})
}

// CLUBNAMEContains applies the Contains predicate on the "CLUB_NAME" field.
func CLUBNAMEContains(v string) predicate.Club {
	return predicate.Club(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldCLUBNAME), v))
	})
}

// CLUBNAMEHasPrefix applies the HasPrefix predicate on the "CLUB_NAME" field.
func CLUBNAMEHasPrefix(v string) predicate.Club {
	return predicate.Club(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldCLUBNAME), v))
	})
}

// CLUBNAMEHasSuffix applies the HasSuffix predicate on the "CLUB_NAME" field.
func CLUBNAMEHasSuffix(v string) predicate.Club {
	return predicate.Club(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldCLUBNAME), v))
	})
}

// CLUBNAMEEqualFold applies the EqualFold predicate on the "CLUB_NAME" field.
func CLUBNAMEEqualFold(v string) predicate.Club {
	return predicate.Club(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldCLUBNAME), v))
	})
}

// CLUBNAMEContainsFold applies the ContainsFold predicate on the "CLUB_NAME" field.
func CLUBNAMEContainsFold(v string) predicate.Club {
	return predicate.Club(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldCLUBNAME), v))
	})
}

// HasLocation applies the HasEdge predicate on the "location" edge.
func HasLocation() predicate.Club {
	return predicate.Club(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(LocationTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, LocationTable, LocationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLocationWith applies the HasEdge predicate on the "location" edge with a given conditions (other predicates).
func HasLocationWith(preds ...predicate.Location) predicate.Club {
	return predicate.Club(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(LocationInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, LocationTable, LocationColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasClubtypes applies the HasEdge predicate on the "clubtypes" edge.
func HasClubtypes() predicate.Club {
	return predicate.Club(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ClubtypesTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ClubtypesTable, ClubtypesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasClubtypesWith applies the HasEdge predicate on the "clubtypes" edge with a given conditions (other predicates).
func HasClubtypesWith(preds ...predicate.ClubTypes) predicate.Club {
	return predicate.Club(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ClubtypesInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ClubtypesTable, ClubtypesColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Club {
	return predicate.Club(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(UserTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Club {
	return predicate.Club(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(UserInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasActivity applies the HasEdge predicate on the "activity" edge.
func HasActivity() predicate.Club {
	return predicate.Club(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ActivityTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ActivityTable, ActivityColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasActivityWith applies the HasEdge predicate on the "activity" edge with a given conditions (other predicates).
func HasActivityWith(preds ...predicate.Activity) predicate.Club {
	return predicate.Club(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ActivityInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ActivityTable, ActivityColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Club) predicate.Club {
	return predicate.Club(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Club) predicate.Club {
	return predicate.Club(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Club) predicate.Club {
	return predicate.Club(func(s *sql.Selector) {
		p(s.Not())
	})
}
