// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Activity is the predicate function for activity builders.
type Activity func(*sql.Selector)

// Club is the predicate function for club builders.
type Club func(*sql.Selector)

// ClubTypes is the predicate function for clubtypes builders.
type ClubTypes func(*sql.Selector)

// Location is the predicate function for location builders.
type Location func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
