// Code generated by entc, DO NOT EDIT.

package activity

const (
	// Label holds the string label denoting the activity type in the database.
	Label = "activity"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCLUBEACTIVITYNAME holds the string denoting the clube_activity_name field in the database.
	FieldCLUBEACTIVITYNAME = "clube_activity_name"

	// EdgeClub holds the string denoting the club edge name in mutations.
	EdgeClub = "club"

	// Table holds the table name of the activity in the database.
	Table = "activities"
	// ClubTable is the table the holds the club relation/edge.
	ClubTable = "clubs"
	// ClubInverseTable is the table name for the Club entity.
	// It exists in this package in order to avoid circular dependency with the "club" package.
	ClubInverseTable = "clubs"
	// ClubColumn is the table column denoting the club relation/edge.
	ClubColumn = "activity_id"
)

// Columns holds all SQL columns for activity fields.
var Columns = []string{
	FieldID,
	FieldCLUBEACTIVITYNAME,
}

var (
	// CLUBEACTIVITYNAMEValidator is a validator for the "CLUBE_ACTIVITY_NAME" field. It is called by the builders before save.
	CLUBEACTIVITYNAMEValidator func(string) error
)
