// Code generated by entc, DO NOT EDIT.

package activity

import (
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/pattapong1/app/ent/predicate"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Activity {
	return predicate.Activity(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Activity {
	return predicate.Activity(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Activity {
	return predicate.Activity(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Activity {
	return predicate.Activity(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Activity {
	return predicate.Activity(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Activity {
	return predicate.Activity(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Activity {
	return predicate.Activity(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Activity {
	return predicate.Activity(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Activity {
	return predicate.Activity(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// CLUBEACTIVITYNAME applies equality check predicate on the "CLUBE_ACTIVITY_NAME" field. It's identical to CLUBEACTIVITYNAMEEQ.
func CLUBEACTIVITYNAME(v string) predicate.Activity {
	return predicate.Activity(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCLUBEACTIVITYNAME), v))
	})
}

// CLUBEACTIVITYNAMEEQ applies the EQ predicate on the "CLUBE_ACTIVITY_NAME" field.
func CLUBEACTIVITYNAMEEQ(v string) predicate.Activity {
	return predicate.Activity(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCLUBEACTIVITYNAME), v))
	})
}

// CLUBEACTIVITYNAMENEQ applies the NEQ predicate on the "CLUBE_ACTIVITY_NAME" field.
func CLUBEACTIVITYNAMENEQ(v string) predicate.Activity {
	return predicate.Activity(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCLUBEACTIVITYNAME), v))
	})
}

// CLUBEACTIVITYNAMEIn applies the In predicate on the "CLUBE_ACTIVITY_NAME" field.
func CLUBEACTIVITYNAMEIn(vs ...string) predicate.Activity {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Activity(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldCLUBEACTIVITYNAME), v...))
	})
}

// CLUBEACTIVITYNAMENotIn applies the NotIn predicate on the "CLUBE_ACTIVITY_NAME" field.
func CLUBEACTIVITYNAMENotIn(vs ...string) predicate.Activity {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Activity(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldCLUBEACTIVITYNAME), v...))
	})
}

// CLUBEACTIVITYNAMEGT applies the GT predicate on the "CLUBE_ACTIVITY_NAME" field.
func CLUBEACTIVITYNAMEGT(v string) predicate.Activity {
	return predicate.Activity(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCLUBEACTIVITYNAME), v))
	})
}

// CLUBEACTIVITYNAMEGTE applies the GTE predicate on the "CLUBE_ACTIVITY_NAME" field.
func CLUBEACTIVITYNAMEGTE(v string) predicate.Activity {
	return predicate.Activity(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCLUBEACTIVITYNAME), v))
	})
}

// CLUBEACTIVITYNAMELT applies the LT predicate on the "CLUBE_ACTIVITY_NAME" field.
func CLUBEACTIVITYNAMELT(v string) predicate.Activity {
	return predicate.Activity(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCLUBEACTIVITYNAME), v))
	})
}

// CLUBEACTIVITYNAMELTE applies the LTE predicate on the "CLUBE_ACTIVITY_NAME" field.
func CLUBEACTIVITYNAMELTE(v string) predicate.Activity {
	return predicate.Activity(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCLUBEACTIVITYNAME), v))
	})
}

// CLUBEACTIVITYNAMEContains applies the Contains predicate on the "CLUBE_ACTIVITY_NAME" field.
func CLUBEACTIVITYNAMEContains(v string) predicate.Activity {
	return predicate.Activity(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldCLUBEACTIVITYNAME), v))
	})
}

// CLUBEACTIVITYNAMEHasPrefix applies the HasPrefix predicate on the "CLUBE_ACTIVITY_NAME" field.
func CLUBEACTIVITYNAMEHasPrefix(v string) predicate.Activity {
	return predicate.Activity(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldCLUBEACTIVITYNAME), v))
	})
}

// CLUBEACTIVITYNAMEHasSuffix applies the HasSuffix predicate on the "CLUBE_ACTIVITY_NAME" field.
func CLUBEACTIVITYNAMEHasSuffix(v string) predicate.Activity {
	return predicate.Activity(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldCLUBEACTIVITYNAME), v))
	})
}

// CLUBEACTIVITYNAMEEqualFold applies the EqualFold predicate on the "CLUBE_ACTIVITY_NAME" field.
func CLUBEACTIVITYNAMEEqualFold(v string) predicate.Activity {
	return predicate.Activity(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldCLUBEACTIVITYNAME), v))
	})
}

// CLUBEACTIVITYNAMEContainsFold applies the ContainsFold predicate on the "CLUBE_ACTIVITY_NAME" field.
func CLUBEACTIVITYNAMEContainsFold(v string) predicate.Activity {
	return predicate.Activity(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldCLUBEACTIVITYNAME), v))
	})
}

// HasClub applies the HasEdge predicate on the "club" edge.
func HasClub() predicate.Activity {
	return predicate.Activity(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ClubTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ClubTable, ClubColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasClubWith applies the HasEdge predicate on the "club" edge with a given conditions (other predicates).
func HasClubWith(preds ...predicate.Club) predicate.Activity {
	return predicate.Activity(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ClubInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ClubTable, ClubColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Activity) predicate.Activity {
	return predicate.Activity(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Activity) predicate.Activity {
	return predicate.Activity(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Activity) predicate.Activity {
	return predicate.Activity(func(s *sql.Selector) {
		p(s.Not())
	})
}
