// Code generated by entc, DO NOT EDIT.

package location

const (
	// Label holds the string label denoting the location type in the database.
	Label = "location"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCLUBELOCATIONNAME holds the string denoting the clube_location_name field in the database.
	FieldCLUBELOCATIONNAME = "clube_location_name"
	// FieldCLUBELOCATIONADDRESS holds the string denoting the clube_location_address field in the database.
	FieldCLUBELOCATIONADDRESS = "clube_location_address"

	// EdgeClub holds the string denoting the club edge name in mutations.
	EdgeClub = "club"

	// Table holds the table name of the location in the database.
	Table = "locations"
	// ClubTable is the table the holds the club relation/edge.
	ClubTable = "clubs"
	// ClubInverseTable is the table name for the Club entity.
	// It exists in this package in order to avoid circular dependency with the "club" package.
	ClubInverseTable = "clubs"
	// ClubColumn is the table column denoting the club relation/edge.
	ClubColumn = "location_id"
)

// Columns holds all SQL columns for location fields.
var Columns = []string{
	FieldID,
	FieldCLUBELOCATIONNAME,
	FieldCLUBELOCATIONADDRESS,
}

var (
	// CLUBELOCATIONNAMEValidator is a validator for the "CLUBE_LOCATION_NAME" field. It is called by the builders before save.
	CLUBELOCATIONNAMEValidator func(string) error
	// CLUBELOCATIONADDRESSValidator is a validator for the "CLUBE_LOCATION_ADDRESS" field. It is called by the builders before save.
	CLUBELOCATIONADDRESSValidator func(string) error
)
