// Code generated by entc, DO NOT EDIT.

package location

import (
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/pattapong1/app/ent/predicate"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Location {
	return predicate.Location(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Location {
	return predicate.Location(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Location {
	return predicate.Location(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Location {
	return predicate.Location(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Location {
	return predicate.Location(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Location {
	return predicate.Location(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Location {
	return predicate.Location(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Location {
	return predicate.Location(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Location {
	return predicate.Location(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// CLUBELOCATIONNAME applies equality check predicate on the "CLUBE_LOCATION_NAME" field. It's identical to CLUBELOCATIONNAMEEQ.
func CLUBELOCATIONNAME(v string) predicate.Location {
	return predicate.Location(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCLUBELOCATIONNAME), v))
	})
}

// CLUBELOCATIONADDRESS applies equality check predicate on the "CLUBE_LOCATION_ADDRESS" field. It's identical to CLUBELOCATIONADDRESSEQ.
func CLUBELOCATIONADDRESS(v string) predicate.Location {
	return predicate.Location(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCLUBELOCATIONADDRESS), v))
	})
}

// CLUBELOCATIONNAMEEQ applies the EQ predicate on the "CLUBE_LOCATION_NAME" field.
func CLUBELOCATIONNAMEEQ(v string) predicate.Location {
	return predicate.Location(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCLUBELOCATIONNAME), v))
	})
}

// CLUBELOCATIONNAMENEQ applies the NEQ predicate on the "CLUBE_LOCATION_NAME" field.
func CLUBELOCATIONNAMENEQ(v string) predicate.Location {
	return predicate.Location(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCLUBELOCATIONNAME), v))
	})
}

// CLUBELOCATIONNAMEIn applies the In predicate on the "CLUBE_LOCATION_NAME" field.
func CLUBELOCATIONNAMEIn(vs ...string) predicate.Location {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Location(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldCLUBELOCATIONNAME), v...))
	})
}

// CLUBELOCATIONNAMENotIn applies the NotIn predicate on the "CLUBE_LOCATION_NAME" field.
func CLUBELOCATIONNAMENotIn(vs ...string) predicate.Location {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Location(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldCLUBELOCATIONNAME), v...))
	})
}

// CLUBELOCATIONNAMEGT applies the GT predicate on the "CLUBE_LOCATION_NAME" field.
func CLUBELOCATIONNAMEGT(v string) predicate.Location {
	return predicate.Location(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCLUBELOCATIONNAME), v))
	})
}

// CLUBELOCATIONNAMEGTE applies the GTE predicate on the "CLUBE_LOCATION_NAME" field.
func CLUBELOCATIONNAMEGTE(v string) predicate.Location {
	return predicate.Location(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCLUBELOCATIONNAME), v))
	})
}

// CLUBELOCATIONNAMELT applies the LT predicate on the "CLUBE_LOCATION_NAME" field.
func CLUBELOCATIONNAMELT(v string) predicate.Location {
	return predicate.Location(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCLUBELOCATIONNAME), v))
	})
}

// CLUBELOCATIONNAMELTE applies the LTE predicate on the "CLUBE_LOCATION_NAME" field.
func CLUBELOCATIONNAMELTE(v string) predicate.Location {
	return predicate.Location(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCLUBELOCATIONNAME), v))
	})
}

// CLUBELOCATIONNAMEContains applies the Contains predicate on the "CLUBE_LOCATION_NAME" field.
func CLUBELOCATIONNAMEContains(v string) predicate.Location {
	return predicate.Location(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldCLUBELOCATIONNAME), v))
	})
}

// CLUBELOCATIONNAMEHasPrefix applies the HasPrefix predicate on the "CLUBE_LOCATION_NAME" field.
func CLUBELOCATIONNAMEHasPrefix(v string) predicate.Location {
	return predicate.Location(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldCLUBELOCATIONNAME), v))
	})
}

// CLUBELOCATIONNAMEHasSuffix applies the HasSuffix predicate on the "CLUBE_LOCATION_NAME" field.
func CLUBELOCATIONNAMEHasSuffix(v string) predicate.Location {
	return predicate.Location(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldCLUBELOCATIONNAME), v))
	})
}

// CLUBELOCATIONNAMEEqualFold applies the EqualFold predicate on the "CLUBE_LOCATION_NAME" field.
func CLUBELOCATIONNAMEEqualFold(v string) predicate.Location {
	return predicate.Location(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldCLUBELOCATIONNAME), v))
	})
}

// CLUBELOCATIONNAMEContainsFold applies the ContainsFold predicate on the "CLUBE_LOCATION_NAME" field.
func CLUBELOCATIONNAMEContainsFold(v string) predicate.Location {
	return predicate.Location(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldCLUBELOCATIONNAME), v))
	})
}

// CLUBELOCATIONADDRESSEQ applies the EQ predicate on the "CLUBE_LOCATION_ADDRESS" field.
func CLUBELOCATIONADDRESSEQ(v string) predicate.Location {
	return predicate.Location(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCLUBELOCATIONADDRESS), v))
	})
}

// CLUBELOCATIONADDRESSNEQ applies the NEQ predicate on the "CLUBE_LOCATION_ADDRESS" field.
func CLUBELOCATIONADDRESSNEQ(v string) predicate.Location {
	return predicate.Location(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCLUBELOCATIONADDRESS), v))
	})
}

// CLUBELOCATIONADDRESSIn applies the In predicate on the "CLUBE_LOCATION_ADDRESS" field.
func CLUBELOCATIONADDRESSIn(vs ...string) predicate.Location {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Location(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldCLUBELOCATIONADDRESS), v...))
	})
}

// CLUBELOCATIONADDRESSNotIn applies the NotIn predicate on the "CLUBE_LOCATION_ADDRESS" field.
func CLUBELOCATIONADDRESSNotIn(vs ...string) predicate.Location {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Location(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldCLUBELOCATIONADDRESS), v...))
	})
}

// CLUBELOCATIONADDRESSGT applies the GT predicate on the "CLUBE_LOCATION_ADDRESS" field.
func CLUBELOCATIONADDRESSGT(v string) predicate.Location {
	return predicate.Location(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCLUBELOCATIONADDRESS), v))
	})
}

// CLUBELOCATIONADDRESSGTE applies the GTE predicate on the "CLUBE_LOCATION_ADDRESS" field.
func CLUBELOCATIONADDRESSGTE(v string) predicate.Location {
	return predicate.Location(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCLUBELOCATIONADDRESS), v))
	})
}

// CLUBELOCATIONADDRESSLT applies the LT predicate on the "CLUBE_LOCATION_ADDRESS" field.
func CLUBELOCATIONADDRESSLT(v string) predicate.Location {
	return predicate.Location(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCLUBELOCATIONADDRESS), v))
	})
}

// CLUBELOCATIONADDRESSLTE applies the LTE predicate on the "CLUBE_LOCATION_ADDRESS" field.
func CLUBELOCATIONADDRESSLTE(v string) predicate.Location {
	return predicate.Location(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCLUBELOCATIONADDRESS), v))
	})
}

// CLUBELOCATIONADDRESSContains applies the Contains predicate on the "CLUBE_LOCATION_ADDRESS" field.
func CLUBELOCATIONADDRESSContains(v string) predicate.Location {
	return predicate.Location(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldCLUBELOCATIONADDRESS), v))
	})
}

// CLUBELOCATIONADDRESSHasPrefix applies the HasPrefix predicate on the "CLUBE_LOCATION_ADDRESS" field.
func CLUBELOCATIONADDRESSHasPrefix(v string) predicate.Location {
	return predicate.Location(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldCLUBELOCATIONADDRESS), v))
	})
}

// CLUBELOCATIONADDRESSHasSuffix applies the HasSuffix predicate on the "CLUBE_LOCATION_ADDRESS" field.
func CLUBELOCATIONADDRESSHasSuffix(v string) predicate.Location {
	return predicate.Location(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldCLUBELOCATIONADDRESS), v))
	})
}

// CLUBELOCATIONADDRESSEqualFold applies the EqualFold predicate on the "CLUBE_LOCATION_ADDRESS" field.
func CLUBELOCATIONADDRESSEqualFold(v string) predicate.Location {
	return predicate.Location(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldCLUBELOCATIONADDRESS), v))
	})
}

// CLUBELOCATIONADDRESSContainsFold applies the ContainsFold predicate on the "CLUBE_LOCATION_ADDRESS" field.
func CLUBELOCATIONADDRESSContainsFold(v string) predicate.Location {
	return predicate.Location(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldCLUBELOCATIONADDRESS), v))
	})
}

// HasClub applies the HasEdge predicate on the "club" edge.
func HasClub() predicate.Location {
	return predicate.Location(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ClubTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ClubTable, ClubColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasClubWith applies the HasEdge predicate on the "club" edge with a given conditions (other predicates).
func HasClubWith(preds ...predicate.Club) predicate.Location {
	return predicate.Location(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ClubInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ClubTable, ClubColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Location) predicate.Location {
	return predicate.Location(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Location) predicate.Location {
	return predicate.Location(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Location) predicate.Location {
	return predicate.Location(func(s *sql.Selector) {
		p(s.Not())
	})
}
