// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/pattapong1/app/ent/activity"
	"github.com/pattapong1/app/ent/club"
)

// ActivityCreate is the builder for creating a Activity entity.
type ActivityCreate struct {
	config
	mutation *ActivityMutation
	hooks    []Hook
}

// SetCLUBEACTIVITYNAME sets the CLUBE_ACTIVITY_NAME field.
func (ac *ActivityCreate) SetCLUBEACTIVITYNAME(s string) *ActivityCreate {
	ac.mutation.SetCLUBEACTIVITYNAME(s)
	return ac
}

// AddClubIDs adds the club edge to Club by ids.
func (ac *ActivityCreate) AddClubIDs(ids ...int) *ActivityCreate {
	ac.mutation.AddClubIDs(ids...)
	return ac
}

// AddClub adds the club edges to Club.
func (ac *ActivityCreate) AddClub(c ...*Club) *ActivityCreate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return ac.AddClubIDs(ids...)
}

// Mutation returns the ActivityMutation object of the builder.
func (ac *ActivityCreate) Mutation() *ActivityMutation {
	return ac.mutation
}

// Save creates the Activity in the database.
func (ac *ActivityCreate) Save(ctx context.Context) (*Activity, error) {
	if _, ok := ac.mutation.CLUBEACTIVITYNAME(); !ok {
		return nil, &ValidationError{Name: "CLUBE_ACTIVITY_NAME", err: errors.New("ent: missing required field \"CLUBE_ACTIVITY_NAME\"")}
	}
	if v, ok := ac.mutation.CLUBEACTIVITYNAME(); ok {
		if err := activity.CLUBEACTIVITYNAMEValidator(v); err != nil {
			return nil, &ValidationError{Name: "CLUBE_ACTIVITY_NAME", err: fmt.Errorf("ent: validator failed for field \"CLUBE_ACTIVITY_NAME\": %w", err)}
		}
	}
	var (
		err  error
		node *Activity
	)
	if len(ac.hooks) == 0 {
		node, err = ac.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ActivityMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ac.mutation = mutation
			node, err = ac.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(ac.hooks) - 1; i >= 0; i-- {
			mut = ac.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ac.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ac *ActivityCreate) SaveX(ctx context.Context) *Activity {
	v, err := ac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ac *ActivityCreate) sqlSave(ctx context.Context) (*Activity, error) {
	a, _spec := ac.createSpec()
	if err := sqlgraph.CreateNode(ctx, ac.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	a.ID = int(id)
	return a, nil
}

func (ac *ActivityCreate) createSpec() (*Activity, *sqlgraph.CreateSpec) {
	var (
		a     = &Activity{config: ac.config}
		_spec = &sqlgraph.CreateSpec{
			Table: activity.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: activity.FieldID,
			},
		}
	)
	if value, ok := ac.mutation.CLUBEACTIVITYNAME(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: activity.FieldCLUBEACTIVITYNAME,
		})
		a.CLUBEACTIVITYNAME = value
	}
	if nodes := ac.mutation.ClubIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   activity.ClubTable,
			Columns: []string{activity.ClubColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: club.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return a, _spec
}
