// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/pattapong1/app/ent/club"
	"github.com/pattapong1/app/ent/clubtypes"
	"github.com/pattapong1/app/ent/predicate"
)

// ClubTypesUpdate is the builder for updating ClubTypes entities.
type ClubTypesUpdate struct {
	config
	hooks      []Hook
	mutation   *ClubTypesMutation
	predicates []predicate.ClubTypes
}

// Where adds a new predicate for the builder.
func (ctu *ClubTypesUpdate) Where(ps ...predicate.ClubTypes) *ClubTypesUpdate {
	ctu.predicates = append(ctu.predicates, ps...)
	return ctu
}

// SetCLUBETYPENAME sets the CLUBE_TYPE_NAME field.
func (ctu *ClubTypesUpdate) SetCLUBETYPENAME(s string) *ClubTypesUpdate {
	ctu.mutation.SetCLUBETYPENAME(s)
	return ctu
}

// AddClubIDs adds the club edge to Club by ids.
func (ctu *ClubTypesUpdate) AddClubIDs(ids ...int) *ClubTypesUpdate {
	ctu.mutation.AddClubIDs(ids...)
	return ctu
}

// AddClub adds the club edges to Club.
func (ctu *ClubTypesUpdate) AddClub(c ...*Club) *ClubTypesUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return ctu.AddClubIDs(ids...)
}

// Mutation returns the ClubTypesMutation object of the builder.
func (ctu *ClubTypesUpdate) Mutation() *ClubTypesMutation {
	return ctu.mutation
}

// RemoveClubIDs removes the club edge to Club by ids.
func (ctu *ClubTypesUpdate) RemoveClubIDs(ids ...int) *ClubTypesUpdate {
	ctu.mutation.RemoveClubIDs(ids...)
	return ctu
}

// RemoveClub removes club edges to Club.
func (ctu *ClubTypesUpdate) RemoveClub(c ...*Club) *ClubTypesUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return ctu.RemoveClubIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (ctu *ClubTypesUpdate) Save(ctx context.Context) (int, error) {
	if v, ok := ctu.mutation.CLUBETYPENAME(); ok {
		if err := clubtypes.CLUBETYPENAMEValidator(v); err != nil {
			return 0, &ValidationError{Name: "CLUBE_TYPE_NAME", err: fmt.Errorf("ent: validator failed for field \"CLUBE_TYPE_NAME\": %w", err)}
		}
	}

	var (
		err      error
		affected int
	)
	if len(ctu.hooks) == 0 {
		affected, err = ctu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ClubTypesMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ctu.mutation = mutation
			affected, err = ctu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ctu.hooks) - 1; i >= 0; i-- {
			mut = ctu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ctu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (ctu *ClubTypesUpdate) SaveX(ctx context.Context) int {
	affected, err := ctu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ctu *ClubTypesUpdate) Exec(ctx context.Context) error {
	_, err := ctu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ctu *ClubTypesUpdate) ExecX(ctx context.Context) {
	if err := ctu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ctu *ClubTypesUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   clubtypes.Table,
			Columns: clubtypes.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: clubtypes.FieldID,
			},
		},
	}
	if ps := ctu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ctu.mutation.CLUBETYPENAME(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: clubtypes.FieldCLUBETYPENAME,
		})
	}
	if nodes := ctu.mutation.RemovedClubIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   clubtypes.ClubTable,
			Columns: []string{clubtypes.ClubColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: club.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ctu.mutation.ClubIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   clubtypes.ClubTable,
			Columns: []string{clubtypes.ClubColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: club.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ctu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{clubtypes.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// ClubTypesUpdateOne is the builder for updating a single ClubTypes entity.
type ClubTypesUpdateOne struct {
	config
	hooks    []Hook
	mutation *ClubTypesMutation
}

// SetCLUBETYPENAME sets the CLUBE_TYPE_NAME field.
func (ctuo *ClubTypesUpdateOne) SetCLUBETYPENAME(s string) *ClubTypesUpdateOne {
	ctuo.mutation.SetCLUBETYPENAME(s)
	return ctuo
}

// AddClubIDs adds the club edge to Club by ids.
func (ctuo *ClubTypesUpdateOne) AddClubIDs(ids ...int) *ClubTypesUpdateOne {
	ctuo.mutation.AddClubIDs(ids...)
	return ctuo
}

// AddClub adds the club edges to Club.
func (ctuo *ClubTypesUpdateOne) AddClub(c ...*Club) *ClubTypesUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return ctuo.AddClubIDs(ids...)
}

// Mutation returns the ClubTypesMutation object of the builder.
func (ctuo *ClubTypesUpdateOne) Mutation() *ClubTypesMutation {
	return ctuo.mutation
}

// RemoveClubIDs removes the club edge to Club by ids.
func (ctuo *ClubTypesUpdateOne) RemoveClubIDs(ids ...int) *ClubTypesUpdateOne {
	ctuo.mutation.RemoveClubIDs(ids...)
	return ctuo
}

// RemoveClub removes club edges to Club.
func (ctuo *ClubTypesUpdateOne) RemoveClub(c ...*Club) *ClubTypesUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return ctuo.RemoveClubIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (ctuo *ClubTypesUpdateOne) Save(ctx context.Context) (*ClubTypes, error) {
	if v, ok := ctuo.mutation.CLUBETYPENAME(); ok {
		if err := clubtypes.CLUBETYPENAMEValidator(v); err != nil {
			return nil, &ValidationError{Name: "CLUBE_TYPE_NAME", err: fmt.Errorf("ent: validator failed for field \"CLUBE_TYPE_NAME\": %w", err)}
		}
	}

	var (
		err  error
		node *ClubTypes
	)
	if len(ctuo.hooks) == 0 {
		node, err = ctuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ClubTypesMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ctuo.mutation = mutation
			node, err = ctuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(ctuo.hooks) - 1; i >= 0; i-- {
			mut = ctuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ctuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (ctuo *ClubTypesUpdateOne) SaveX(ctx context.Context) *ClubTypes {
	ct, err := ctuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return ct
}

// Exec executes the query on the entity.
func (ctuo *ClubTypesUpdateOne) Exec(ctx context.Context) error {
	_, err := ctuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ctuo *ClubTypesUpdateOne) ExecX(ctx context.Context) {
	if err := ctuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ctuo *ClubTypesUpdateOne) sqlSave(ctx context.Context) (ct *ClubTypes, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   clubtypes.Table,
			Columns: clubtypes.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: clubtypes.FieldID,
			},
		},
	}
	id, ok := ctuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing ClubTypes.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := ctuo.mutation.CLUBETYPENAME(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: clubtypes.FieldCLUBETYPENAME,
		})
	}
	if nodes := ctuo.mutation.RemovedClubIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   clubtypes.ClubTable,
			Columns: []string{clubtypes.ClubColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: club.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ctuo.mutation.ClubIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   clubtypes.ClubTable,
			Columns: []string{clubtypes.ClubColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: club.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	ct = &ClubTypes{config: ctuo.config}
	_spec.Assign = ct.assignValues
	_spec.ScanValues = ct.scanValues()
	if err = sqlgraph.UpdateNode(ctx, ctuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{clubtypes.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return ct, nil
}
