// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/pattapong1/app/ent/clubtypes"
)

// ClubTypes is the model entity for the ClubTypes schema.
type ClubTypes struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CLUBETYPENAME holds the value of the "CLUBE_TYPE_NAME" field.
	CLUBETYPENAME string `json:"CLUBE_TYPE_NAME,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ClubTypesQuery when eager-loading is set.
	Edges ClubTypesEdges `json:"edges"`
}

// ClubTypesEdges holds the relations/edges for other nodes in the graph.
type ClubTypesEdges struct {
	// Club holds the value of the club edge.
	Club []*Club
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ClubOrErr returns the Club value or an error if the edge
// was not loaded in eager-loading.
func (e ClubTypesEdges) ClubOrErr() ([]*Club, error) {
	if e.loadedTypes[0] {
		return e.Club, nil
	}
	return nil, &NotLoadedError{edge: "club"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ClubTypes) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // CLUBE_TYPE_NAME
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ClubTypes fields.
func (ct *ClubTypes) assignValues(values ...interface{}) error {
	if m, n := len(values), len(clubtypes.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	ct.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field CLUBE_TYPE_NAME", values[0])
	} else if value.Valid {
		ct.CLUBETYPENAME = value.String
	}
	return nil
}

// QueryClub queries the club edge of the ClubTypes.
func (ct *ClubTypes) QueryClub() *ClubQuery {
	return (&ClubTypesClient{config: ct.config}).QueryClub(ct)
}

// Update returns a builder for updating this ClubTypes.
// Note that, you need to call ClubTypes.Unwrap() before calling this method, if this ClubTypes
// was returned from a transaction, and the transaction was committed or rolled back.
func (ct *ClubTypes) Update() *ClubTypesUpdateOne {
	return (&ClubTypesClient{config: ct.config}).UpdateOne(ct)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (ct *ClubTypes) Unwrap() *ClubTypes {
	tx, ok := ct.config.driver.(*txDriver)
	if !ok {
		panic("ent: ClubTypes is not a transactional entity")
	}
	ct.config.driver = tx.drv
	return ct
}

// String implements the fmt.Stringer.
func (ct *ClubTypes) String() string {
	var builder strings.Builder
	builder.WriteString("ClubTypes(")
	builder.WriteString(fmt.Sprintf("id=%v", ct.ID))
	builder.WriteString(", CLUBE_TYPE_NAME=")
	builder.WriteString(ct.CLUBETYPENAME)
	builder.WriteByte(')')
	return builder.String()
}

// ClubTypesSlice is a parsable slice of ClubTypes.
type ClubTypesSlice []*ClubTypes

func (ct ClubTypesSlice) config(cfg config) {
	for _i := range ct {
		ct[_i].config = cfg
	}
}
