// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"math"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/pattapong1/app/ent/club"
	"github.com/pattapong1/app/ent/clubtypes"
	"github.com/pattapong1/app/ent/predicate"
)

// ClubTypesQuery is the builder for querying ClubTypes entities.
type ClubTypesQuery struct {
	config
	limit      *int
	offset     *int
	order      []OrderFunc
	unique     []string
	predicates []predicate.ClubTypes
	// eager-loading edges.
	withClub *ClubQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the builder.
func (ctq *ClubTypesQuery) Where(ps ...predicate.ClubTypes) *ClubTypesQuery {
	ctq.predicates = append(ctq.predicates, ps...)
	return ctq
}

// Limit adds a limit step to the query.
func (ctq *ClubTypesQuery) Limit(limit int) *ClubTypesQuery {
	ctq.limit = &limit
	return ctq
}

// Offset adds an offset step to the query.
func (ctq *ClubTypesQuery) Offset(offset int) *ClubTypesQuery {
	ctq.offset = &offset
	return ctq
}

// Order adds an order step to the query.
func (ctq *ClubTypesQuery) Order(o ...OrderFunc) *ClubTypesQuery {
	ctq.order = append(ctq.order, o...)
	return ctq
}

// QueryClub chains the current query on the club edge.
func (ctq *ClubTypesQuery) QueryClub() *ClubQuery {
	query := &ClubQuery{config: ctq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ctq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(clubtypes.Table, clubtypes.FieldID, ctq.sqlQuery()),
			sqlgraph.To(club.Table, club.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, clubtypes.ClubTable, clubtypes.ClubColumn),
		)
		fromU = sqlgraph.SetNeighbors(ctq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ClubTypes entity in the query. Returns *NotFoundError when no clubtypes was found.
func (ctq *ClubTypesQuery) First(ctx context.Context) (*ClubTypes, error) {
	cts, err := ctq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(cts) == 0 {
		return nil, &NotFoundError{clubtypes.Label}
	}
	return cts[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ctq *ClubTypesQuery) FirstX(ctx context.Context) *ClubTypes {
	ct, err := ctq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return ct
}

// FirstID returns the first ClubTypes id in the query. Returns *NotFoundError when no id was found.
func (ctq *ClubTypesQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ctq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{clubtypes.Label}
		return
	}
	return ids[0], nil
}

// FirstXID is like FirstID, but panics if an error occurs.
func (ctq *ClubTypesQuery) FirstXID(ctx context.Context) int {
	id, err := ctq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns the only ClubTypes entity in the query, returns an error if not exactly one entity was returned.
func (ctq *ClubTypesQuery) Only(ctx context.Context) (*ClubTypes, error) {
	cts, err := ctq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(cts) {
	case 1:
		return cts[0], nil
	case 0:
		return nil, &NotFoundError{clubtypes.Label}
	default:
		return nil, &NotSingularError{clubtypes.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ctq *ClubTypesQuery) OnlyX(ctx context.Context) *ClubTypes {
	ct, err := ctq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return ct
}

// OnlyID returns the only ClubTypes id in the query, returns an error if not exactly one id was returned.
func (ctq *ClubTypesQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ctq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{clubtypes.Label}
	default:
		err = &NotSingularError{clubtypes.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ctq *ClubTypesQuery) OnlyIDX(ctx context.Context) int {
	id, err := ctq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ClubTypesSlice.
func (ctq *ClubTypesQuery) All(ctx context.Context) ([]*ClubTypes, error) {
	if err := ctq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return ctq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (ctq *ClubTypesQuery) AllX(ctx context.Context) []*ClubTypes {
	cts, err := ctq.All(ctx)
	if err != nil {
		panic(err)
	}
	return cts
}

// IDs executes the query and returns a list of ClubTypes ids.
func (ctq *ClubTypesQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := ctq.Select(clubtypes.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ctq *ClubTypesQuery) IDsX(ctx context.Context) []int {
	ids, err := ctq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ctq *ClubTypesQuery) Count(ctx context.Context) (int, error) {
	if err := ctq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return ctq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (ctq *ClubTypesQuery) CountX(ctx context.Context) int {
	count, err := ctq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ctq *ClubTypesQuery) Exist(ctx context.Context) (bool, error) {
	if err := ctq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return ctq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (ctq *ClubTypesQuery) ExistX(ctx context.Context) bool {
	exist, err := ctq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the query builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ctq *ClubTypesQuery) Clone() *ClubTypesQuery {
	return &ClubTypesQuery{
		config:     ctq.config,
		limit:      ctq.limit,
		offset:     ctq.offset,
		order:      append([]OrderFunc{}, ctq.order...),
		unique:     append([]string{}, ctq.unique...),
		predicates: append([]predicate.ClubTypes{}, ctq.predicates...),
		// clone intermediate query.
		sql:  ctq.sql.Clone(),
		path: ctq.path,
	}
}

//  WithClub tells the query-builder to eager-loads the nodes that are connected to
// the "club" edge. The optional arguments used to configure the query builder of the edge.
func (ctq *ClubTypesQuery) WithClub(opts ...func(*ClubQuery)) *ClubTypesQuery {
	query := &ClubQuery{config: ctq.config}
	for _, opt := range opts {
		opt(query)
	}
	ctq.withClub = query
	return ctq
}

// GroupBy used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CLUBETYPENAME string `json:"CLUBE_TYPE_NAME,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ClubTypes.Query().
//		GroupBy(clubtypes.FieldCLUBETYPENAME).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (ctq *ClubTypesQuery) GroupBy(field string, fields ...string) *ClubTypesGroupBy {
	group := &ClubTypesGroupBy{config: ctq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := ctq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return ctq.sqlQuery(), nil
	}
	return group
}

// Select one or more fields from the given query.
//
// Example:
//
//	var v []struct {
//		CLUBETYPENAME string `json:"CLUBE_TYPE_NAME,omitempty"`
//	}
//
//	client.ClubTypes.Query().
//		Select(clubtypes.FieldCLUBETYPENAME).
//		Scan(ctx, &v)
//
func (ctq *ClubTypesQuery) Select(field string, fields ...string) *ClubTypesSelect {
	selector := &ClubTypesSelect{config: ctq.config}
	selector.fields = append([]string{field}, fields...)
	selector.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := ctq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return ctq.sqlQuery(), nil
	}
	return selector
}

func (ctq *ClubTypesQuery) prepareQuery(ctx context.Context) error {
	if ctq.path != nil {
		prev, err := ctq.path(ctx)
		if err != nil {
			return err
		}
		ctq.sql = prev
	}
	return nil
}

func (ctq *ClubTypesQuery) sqlAll(ctx context.Context) ([]*ClubTypes, error) {
	var (
		nodes       = []*ClubTypes{}
		_spec       = ctq.querySpec()
		loadedTypes = [1]bool{
			ctq.withClub != nil,
		}
	)
	_spec.ScanValues = func() []interface{} {
		node := &ClubTypes{config: ctq.config}
		nodes = append(nodes, node)
		values := node.scanValues()
		return values
	}
	_spec.Assign = func(values ...interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(values...)
	}
	if err := sqlgraph.QueryNodes(ctx, ctq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := ctq.withClub; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		nodeids := make(map[int]*ClubTypes)
		for i := range nodes {
			fks = append(fks, nodes[i].ID)
			nodeids[nodes[i].ID] = nodes[i]
		}
		query.withFKs = true
		query.Where(predicate.Club(func(s *sql.Selector) {
			s.Where(sql.InValues(clubtypes.ClubColumn, fks...))
		}))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			fk := n.clubtypes_id
			if fk == nil {
				return nil, fmt.Errorf(`foreign-key "clubtypes_id" is nil for node %v`, n.ID)
			}
			node, ok := nodeids[*fk]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "clubtypes_id" returned %v for node %v`, *fk, n.ID)
			}
			node.Edges.Club = append(node.Edges.Club, n)
		}
	}

	return nodes, nil
}

func (ctq *ClubTypesQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ctq.querySpec()
	return sqlgraph.CountNodes(ctx, ctq.driver, _spec)
}

func (ctq *ClubTypesQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := ctq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %v", err)
	}
	return n > 0, nil
}

func (ctq *ClubTypesQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   clubtypes.Table,
			Columns: clubtypes.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: clubtypes.FieldID,
			},
		},
		From:   ctq.sql,
		Unique: true,
	}
	if ps := ctq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ctq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ctq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ctq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ctq *ClubTypesQuery) sqlQuery() *sql.Selector {
	builder := sql.Dialect(ctq.driver.Dialect())
	t1 := builder.Table(clubtypes.Table)
	selector := builder.Select(t1.Columns(clubtypes.Columns...)...).From(t1)
	if ctq.sql != nil {
		selector = ctq.sql
		selector.Select(selector.Columns(clubtypes.Columns...)...)
	}
	for _, p := range ctq.predicates {
		p(selector)
	}
	for _, p := range ctq.order {
		p(selector)
	}
	if offset := ctq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ctq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ClubTypesGroupBy is the builder for group-by ClubTypes entities.
type ClubTypesGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ctgb *ClubTypesGroupBy) Aggregate(fns ...AggregateFunc) *ClubTypesGroupBy {
	ctgb.fns = append(ctgb.fns, fns...)
	return ctgb
}

// Scan applies the group-by query and scan the result into the given value.
func (ctgb *ClubTypesGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := ctgb.path(ctx)
	if err != nil {
		return err
	}
	ctgb.sql = query
	return ctgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ctgb *ClubTypesGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := ctgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by. It is only allowed when querying group-by with one field.
func (ctgb *ClubTypesGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(ctgb.fields) > 1 {
		return nil, errors.New("ent: ClubTypesGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := ctgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ctgb *ClubTypesGroupBy) StringsX(ctx context.Context) []string {
	v, err := ctgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from group-by. It is only allowed when querying group-by with one field.
func (ctgb *ClubTypesGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = ctgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{clubtypes.Label}
	default:
		err = fmt.Errorf("ent: ClubTypesGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (ctgb *ClubTypesGroupBy) StringX(ctx context.Context) string {
	v, err := ctgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by. It is only allowed when querying group-by with one field.
func (ctgb *ClubTypesGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(ctgb.fields) > 1 {
		return nil, errors.New("ent: ClubTypesGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := ctgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ctgb *ClubTypesGroupBy) IntsX(ctx context.Context) []int {
	v, err := ctgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from group-by. It is only allowed when querying group-by with one field.
func (ctgb *ClubTypesGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = ctgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{clubtypes.Label}
	default:
		err = fmt.Errorf("ent: ClubTypesGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (ctgb *ClubTypesGroupBy) IntX(ctx context.Context) int {
	v, err := ctgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by. It is only allowed when querying group-by with one field.
func (ctgb *ClubTypesGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(ctgb.fields) > 1 {
		return nil, errors.New("ent: ClubTypesGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := ctgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ctgb *ClubTypesGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := ctgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from group-by. It is only allowed when querying group-by with one field.
func (ctgb *ClubTypesGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = ctgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{clubtypes.Label}
	default:
		err = fmt.Errorf("ent: ClubTypesGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (ctgb *ClubTypesGroupBy) Float64X(ctx context.Context) float64 {
	v, err := ctgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by. It is only allowed when querying group-by with one field.
func (ctgb *ClubTypesGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(ctgb.fields) > 1 {
		return nil, errors.New("ent: ClubTypesGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := ctgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ctgb *ClubTypesGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := ctgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from group-by. It is only allowed when querying group-by with one field.
func (ctgb *ClubTypesGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = ctgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{clubtypes.Label}
	default:
		err = fmt.Errorf("ent: ClubTypesGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (ctgb *ClubTypesGroupBy) BoolX(ctx context.Context) bool {
	v, err := ctgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ctgb *ClubTypesGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := ctgb.sqlQuery().Query()
	if err := ctgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (ctgb *ClubTypesGroupBy) sqlQuery() *sql.Selector {
	selector := ctgb.sql
	columns := make([]string, 0, len(ctgb.fields)+len(ctgb.fns))
	columns = append(columns, ctgb.fields...)
	for _, fn := range ctgb.fns {
		columns = append(columns, fn(selector))
	}
	return selector.Select(columns...).GroupBy(ctgb.fields...)
}

// ClubTypesSelect is the builder for select fields of ClubTypes entities.
type ClubTypesSelect struct {
	config
	fields []string
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Scan applies the selector query and scan the result into the given value.
func (cts *ClubTypesSelect) Scan(ctx context.Context, v interface{}) error {
	query, err := cts.path(ctx)
	if err != nil {
		return err
	}
	cts.sql = query
	return cts.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (cts *ClubTypesSelect) ScanX(ctx context.Context, v interface{}) {
	if err := cts.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from selector. It is only allowed when selecting one field.
func (cts *ClubTypesSelect) Strings(ctx context.Context) ([]string, error) {
	if len(cts.fields) > 1 {
		return nil, errors.New("ent: ClubTypesSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := cts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (cts *ClubTypesSelect) StringsX(ctx context.Context) []string {
	v, err := cts.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from selector. It is only allowed when selecting one field.
func (cts *ClubTypesSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = cts.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{clubtypes.Label}
	default:
		err = fmt.Errorf("ent: ClubTypesSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (cts *ClubTypesSelect) StringX(ctx context.Context) string {
	v, err := cts.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from selector. It is only allowed when selecting one field.
func (cts *ClubTypesSelect) Ints(ctx context.Context) ([]int, error) {
	if len(cts.fields) > 1 {
		return nil, errors.New("ent: ClubTypesSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := cts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (cts *ClubTypesSelect) IntsX(ctx context.Context) []int {
	v, err := cts.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from selector. It is only allowed when selecting one field.
func (cts *ClubTypesSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = cts.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{clubtypes.Label}
	default:
		err = fmt.Errorf("ent: ClubTypesSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (cts *ClubTypesSelect) IntX(ctx context.Context) int {
	v, err := cts.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from selector. It is only allowed when selecting one field.
func (cts *ClubTypesSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(cts.fields) > 1 {
		return nil, errors.New("ent: ClubTypesSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := cts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (cts *ClubTypesSelect) Float64sX(ctx context.Context) []float64 {
	v, err := cts.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from selector. It is only allowed when selecting one field.
func (cts *ClubTypesSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = cts.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{clubtypes.Label}
	default:
		err = fmt.Errorf("ent: ClubTypesSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (cts *ClubTypesSelect) Float64X(ctx context.Context) float64 {
	v, err := cts.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from selector. It is only allowed when selecting one field.
func (cts *ClubTypesSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(cts.fields) > 1 {
		return nil, errors.New("ent: ClubTypesSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := cts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (cts *ClubTypesSelect) BoolsX(ctx context.Context) []bool {
	v, err := cts.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from selector. It is only allowed when selecting one field.
func (cts *ClubTypesSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = cts.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{clubtypes.Label}
	default:
		err = fmt.Errorf("ent: ClubTypesSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (cts *ClubTypesSelect) BoolX(ctx context.Context) bool {
	v, err := cts.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (cts *ClubTypesSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := cts.sqlQuery().Query()
	if err := cts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (cts *ClubTypesSelect) sqlQuery() sql.Querier {
	selector := cts.sql
	selector.Select(selector.Columns(cts.fields...)...)
	return selector
}
