// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/pattapong1/app/ent/club"
	"github.com/pattapong1/app/ent/clubtypes"
)

// ClubTypesCreate is the builder for creating a ClubTypes entity.
type ClubTypesCreate struct {
	config
	mutation *ClubTypesMutation
	hooks    []Hook
}

// SetCLUBETYPENAME sets the CLUBE_TYPE_NAME field.
func (ctc *ClubTypesCreate) SetCLUBETYPENAME(s string) *ClubTypesCreate {
	ctc.mutation.SetCLUBETYPENAME(s)
	return ctc
}

// AddClubIDs adds the club edge to Club by ids.
func (ctc *ClubTypesCreate) AddClubIDs(ids ...int) *ClubTypesCreate {
	ctc.mutation.AddClubIDs(ids...)
	return ctc
}

// AddClub adds the club edges to Club.
func (ctc *ClubTypesCreate) AddClub(c ...*Club) *ClubTypesCreate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return ctc.AddClubIDs(ids...)
}

// Mutation returns the ClubTypesMutation object of the builder.
func (ctc *ClubTypesCreate) Mutation() *ClubTypesMutation {
	return ctc.mutation
}

// Save creates the ClubTypes in the database.
func (ctc *ClubTypesCreate) Save(ctx context.Context) (*ClubTypes, error) {
	if _, ok := ctc.mutation.CLUBETYPENAME(); !ok {
		return nil, &ValidationError{Name: "CLUBE_TYPE_NAME", err: errors.New("ent: missing required field \"CLUBE_TYPE_NAME\"")}
	}
	if v, ok := ctc.mutation.CLUBETYPENAME(); ok {
		if err := clubtypes.CLUBETYPENAMEValidator(v); err != nil {
			return nil, &ValidationError{Name: "CLUBE_TYPE_NAME", err: fmt.Errorf("ent: validator failed for field \"CLUBE_TYPE_NAME\": %w", err)}
		}
	}
	var (
		err  error
		node *ClubTypes
	)
	if len(ctc.hooks) == 0 {
		node, err = ctc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ClubTypesMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ctc.mutation = mutation
			node, err = ctc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(ctc.hooks) - 1; i >= 0; i-- {
			mut = ctc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ctc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ctc *ClubTypesCreate) SaveX(ctx context.Context) *ClubTypes {
	v, err := ctc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ctc *ClubTypesCreate) sqlSave(ctx context.Context) (*ClubTypes, error) {
	ct, _spec := ctc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ctc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	ct.ID = int(id)
	return ct, nil
}

func (ctc *ClubTypesCreate) createSpec() (*ClubTypes, *sqlgraph.CreateSpec) {
	var (
		ct    = &ClubTypes{config: ctc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: clubtypes.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: clubtypes.FieldID,
			},
		}
	)
	if value, ok := ctc.mutation.CLUBETYPENAME(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: clubtypes.FieldCLUBETYPENAME,
		})
		ct.CLUBETYPENAME = value
	}
	if nodes := ctc.mutation.ClubIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   clubtypes.ClubTable,
			Columns: []string{clubtypes.ClubColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: club.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return ct, _spec
}
