// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/pattapong1/app/ent/activity"
	"github.com/pattapong1/app/ent/club"
	"github.com/pattapong1/app/ent/clubtypes"
	"github.com/pattapong1/app/ent/location"
	"github.com/pattapong1/app/ent/schema"
	"github.com/pattapong1/app/ent/user"
)

// The init function reads all schema descriptors with runtime
// code (default values, validators or hooks) and stitches it
// to their package variables.
func init() {
	activityFields := schema.Activity{}.Fields()
	_ = activityFields
	// activityDescCLUBEACTIVITYNAME is the schema descriptor for CLUBE_ACTIVITY_NAME field.
	activityDescCLUBEACTIVITYNAME := activityFields[0].Descriptor()
	// activity.CLUBEACTIVITYNAMEValidator is a validator for the "CLUBE_ACTIVITY_NAME" field. It is called by the builders before save.
	activity.CLUBEACTIVITYNAMEValidator = activityDescCLUBEACTIVITYNAME.Validators[0].(func(string) error)
	clubFields := schema.Club{}.Fields()
	_ = clubFields
	// clubDescCLUBNAME is the schema descriptor for CLUB_NAME field.
	clubDescCLUBNAME := clubFields[0].Descriptor()
	// club.CLUBNAMEValidator is a validator for the "CLUB_NAME" field. It is called by the builders before save.
	club.CLUBNAMEValidator = clubDescCLUBNAME.Validators[0].(func(string) error)
	clubtypesFields := schema.ClubTypes{}.Fields()
	_ = clubtypesFields
	// clubtypesDescCLUBETYPENAME is the schema descriptor for CLUBE_TYPE_NAME field.
	clubtypesDescCLUBETYPENAME := clubtypesFields[0].Descriptor()
	// clubtypes.CLUBETYPENAMEValidator is a validator for the "CLUBE_TYPE_NAME" field. It is called by the builders before save.
	clubtypes.CLUBETYPENAMEValidator = clubtypesDescCLUBETYPENAME.Validators[0].(func(string) error)
	locationFields := schema.Location{}.Fields()
	_ = locationFields
	// locationDescCLUBELOCATIONNAME is the schema descriptor for CLUBE_LOCATION_NAME field.
	locationDescCLUBELOCATIONNAME := locationFields[0].Descriptor()
	// location.CLUBELOCATIONNAMEValidator is a validator for the "CLUBE_LOCATION_NAME" field. It is called by the builders before save.
	location.CLUBELOCATIONNAMEValidator = locationDescCLUBELOCATIONNAME.Validators[0].(func(string) error)
	// locationDescCLUBELOCATIONADDRESS is the schema descriptor for CLUBE_LOCATION_ADDRESS field.
	locationDescCLUBELOCATIONADDRESS := locationFields[1].Descriptor()
	// location.CLUBELOCATIONADDRESSValidator is a validator for the "CLUBE_LOCATION_ADDRESS" field. It is called by the builders before save.
	location.CLUBELOCATIONADDRESSValidator = locationDescCLUBELOCATIONADDRESS.Validators[0].(func(string) error)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUSERNAME is the schema descriptor for USER_NAME field.
	userDescUSERNAME := userFields[0].Descriptor()
	// user.USERNAMEValidator is a validator for the "USER_NAME" field. It is called by the builders before save.
	user.USERNAMEValidator = userDescUSERNAME.Validators[0].(func(string) error)
	// userDescUSEREMAIL is the schema descriptor for USER_EMAIL field.
	userDescUSEREMAIL := userFields[1].Descriptor()
	// user.USEREMAILValidator is a validator for the "USER_EMAIL" field. It is called by the builders before save.
	user.USEREMAILValidator = userDescUSEREMAIL.Validators[0].(func(string) error)
}
