// Code generated by entc, DO NOT EDIT.

package clubtypes

const (
	// Label holds the string label denoting the clubtypes type in the database.
	Label = "club_types"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCLUBETYPENAME holds the string denoting the clube_type_name field in the database.
	FieldCLUBETYPENAME = "clube_type_name"

	// EdgeClub holds the string denoting the club edge name in mutations.
	EdgeClub = "club"

	// Table holds the table name of the clubtypes in the database.
	Table = "club_types"
	// ClubTable is the table the holds the club relation/edge.
	ClubTable = "clubs"
	// ClubInverseTable is the table name for the Club entity.
	// It exists in this package in order to avoid circular dependency with the "club" package.
	ClubInverseTable = "clubs"
	// ClubColumn is the table column denoting the club relation/edge.
	ClubColumn = "clubtypes_id"
)

// Columns holds all SQL columns for clubtypes fields.
var Columns = []string{
	FieldID,
	FieldCLUBETYPENAME,
}

var (
	// CLUBETYPENAMEValidator is a validator for the "CLUBE_TYPE_NAME" field. It is called by the builders before save.
	CLUBETYPENAMEValidator func(string) error
)
