/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntActivityEdges,
    EntActivityEdgesFromJSON,
    EntActivityEdgesFromJSONTyped,
    EntActivityEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntActivity
 */
export interface EntActivity {
    /**
     * CLUBEACTIVITYNAME holds the value of the "CLUBE_ACTIVITY_NAME" field.
     * @type {string}
     * @memberof EntActivity
     */
    cLUBEACTIVITYNAME?: string;
    /**
     * 
     * @type {EntActivityEdges}
     * @memberof EntActivity
     */
    edges?: EntActivityEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntActivity
     */
    id?: number;
}

export function EntActivityFromJSON(json: any): EntActivity {
    return EntActivityFromJSONTyped(json, false);
}

export function EntActivityFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntActivity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cLUBEACTIVITYNAME': !exists(json, 'CLUBE_ACTIVITY_NAME') ? undefined : json['CLUBE_ACTIVITY_NAME'],
        'edges': !exists(json, 'edges') ? undefined : EntActivityEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntActivityToJSON(value?: EntActivity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'CLUBE_ACTIVITY_NAME': value.cLUBEACTIVITYNAME,
        'edges': EntActivityEdgesToJSON(value.edges),
        'id': value.id,
    };
}


