/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntClubEdges,
    EntClubEdgesFromJSON,
    EntClubEdgesFromJSONTyped,
    EntClubEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntClub
 */
export interface EntClub {
    /**
     * CLUBNAME holds the value of the "CLUB_NAME" field.
     * @type {string}
     * @memberof EntClub
     */
    cLUBNAME?: string;
    /**
     * 
     * @type {EntClubEdges}
     * @memberof EntClub
     */
    edges?: EntClubEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntClub
     */
    id?: number;
}

export function EntClubFromJSON(json: any): EntClub {
    return EntClubFromJSONTyped(json, false);
}

export function EntClubFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntClub {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cLUBNAME': !exists(json, 'CLUB_NAME') ? undefined : json['CLUB_NAME'],
        'edges': !exists(json, 'edges') ? undefined : EntClubEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntClubToJSON(value?: EntClub | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'CLUB_NAME': value.cLUBNAME,
        'edges': EntClubEdgesToJSON(value.edges),
        'id': value.id,
    };
}


