/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntClubTypesEdges,
    EntClubTypesEdgesFromJSON,
    EntClubTypesEdgesFromJSONTyped,
    EntClubTypesEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntClubTypes
 */
export interface EntClubTypes {
    /**
     * CLUBETYPENAME holds the value of the "CLUBE_TYPE_NAME" field.
     * @type {string}
     * @memberof EntClubTypes
     */
    cLUBETYPENAME?: string;
    /**
     * 
     * @type {EntClubTypesEdges}
     * @memberof EntClubTypes
     */
    edges?: EntClubTypesEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntClubTypes
     */
    id?: number;
}

export function EntClubTypesFromJSON(json: any): EntClubTypes {
    return EntClubTypesFromJSONTyped(json, false);
}

export function EntClubTypesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntClubTypes {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cLUBETYPENAME': !exists(json, 'CLUBE_TYPE_NAME') ? undefined : json['CLUBE_TYPE_NAME'],
        'edges': !exists(json, 'edges') ? undefined : EntClubTypesEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntClubTypesToJSON(value?: EntClubTypes | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'CLUBE_TYPE_NAME': value.cLUBETYPENAME,
        'edges': EntClubTypesEdgesToJSON(value.edges),
        'id': value.id,
    };
}


