/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntLocationEdges,
    EntLocationEdgesFromJSON,
    EntLocationEdgesFromJSONTyped,
    EntLocationEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntLocation
 */
export interface EntLocation {
    /**
     * CLUBELOCATIONADDRESS holds the value of the "CLUBE_LOCATION_ADDRESS" field.
     * @type {string}
     * @memberof EntLocation
     */
    cLUBELOCATIONADDRESS?: string;
    /**
     * CLUBELOCATIONNAME holds the value of the "CLUBE_LOCATION_NAME" field.
     * @type {string}
     * @memberof EntLocation
     */
    cLUBELOCATIONNAME?: string;
    /**
     * 
     * @type {EntLocationEdges}
     * @memberof EntLocation
     */
    edges?: EntLocationEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntLocation
     */
    id?: number;
}

export function EntLocationFromJSON(json: any): EntLocation {
    return EntLocationFromJSONTyped(json, false);
}

export function EntLocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntLocation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cLUBELOCATIONADDRESS': !exists(json, 'CLUBE_LOCATION_ADDRESS') ? undefined : json['CLUBE_LOCATION_ADDRESS'],
        'cLUBELOCATIONNAME': !exists(json, 'CLUBE_LOCATION_NAME') ? undefined : json['CLUBE_LOCATION_NAME'],
        'edges': !exists(json, 'edges') ? undefined : EntLocationEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntLocationToJSON(value?: EntLocation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'CLUBE_LOCATION_ADDRESS': value.cLUBELOCATIONADDRESS,
        'CLUBE_LOCATION_NAME': value.cLUBELOCATIONNAME,
        'edges': EntLocationEdgesToJSON(value.edges),
        'id': value.id,
    };
}


